### ISSUE TITLE
Using nmap.md and sqlmap.md

### ISSUE THREAD

**Issue by CodeMaxx** [abhishekjiitr/network-security#5]
Hey @abhishekjiitr . Would you mind if I use the nmap and sqlmap commands from your repository directly in [this repository](https://github.com/CodeMaxx/Terminal-Commands-Beginner) ?

**Comment by abhishek-jaisingh** [comment]
no problem @CodeMaxx ! cheers...

**Comment by CodeMaxx** [comment]
Thanks 😄
